---
title: "combine_new_batch"
author: "Ruwen Zhou"
date: "8/12/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(plyr)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(phyloseq)
library(vegan)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(writexl)
```

```{r}
helios_core_old = read_excel("data/HELIOS_Core_redacted.xlsx")
helios_core_new = read.csv("data/HELIOS2_Core_redacted_300.csv")
helios_core_new$FREG5_Ethnic_Group <- ifelse(helios_core_new$FREG5_Race == "CHINESE", "C",
                                             ifelse(helios_core_new$FREG5_Race == "INDIAN", "I",
                                             ifelse(helios_core_new$FREG5_Race == "MALAY", "M",
                                             ifelse(helios_core_new$FREG5_Race == "Other", "O", NA))))
helios_core_new$FREG7_Gender <- ifelse(helios_core_new$FREG7_Gender == "male", "M",
                                       ifelse(helios_core_new$FREG7_Gender == "female", "F",NA))
                                             


helios_core_old[,c("FREG0_PID", "FREG1_Barcode", "FREG5_Ethnic_Group", "FREG7_Gender", "FREG8_Age", "DBI13_Height", "DBI14_Weight")]
helios_core_new[,c("FREG0_PID", "FREG1_Barcode", "FREG5_Ethnic_Group", "FREG7_Gender", "FREG8_Age", "DBI13_Height", "DBI14_Weight")]
# helios_core_old
# helios_core_new

```
```{r}
library(writexl)
helios800 = rbind(helios_core_new[,c("FREG0_PID", "FREG1_Barcode", "FREG5_Ethnic_Group", "FREG7_Gender", "FREG8_Age", "DBI13_Height", "DBI14_Weight")], helios_core_old[,c("FREG0_PID", "FREG1_Barcode", "FREG5_Ethnic_Group", "FREG7_Gender", "FREG8_Age", "DBI13_Height", "DBI14_Weight")])
helios800
#write_xlsx(helios800, "data/helios800.xlsx")
```
```{r}
helios800$BMI = helios800$DBI14_Weight/(helios800$DBI13_Height*0.01)^2
helios800$BMI_groups <- cut(helios800$BMI, breaks = c(0,18.5,23,25,Inf),
                  labels = c("Underweight", "Normal", "Overweight", "Obese"),
                  include.lowest = TRUE, right = FALSE)
helios800
#write_xlsx(helios800, "data/helios800.xlsx")
```


```{r}
helios_core = read_excel("data/helios800.xlsx")
metadata_micro = read_csv("data/metadata_fil_01032024_redacted.csv")
sample_list = metadata_micro$`Original Sample name`
helios_new <- filter(helios_core, FREG1_Barcode %in% sample_list)
```
#food nutrition
```{r}
# FFQ_food = read_xlsx("data/HELIOS_FFQA.xlsx")
# FFQ_nutrition = read_xlsx("data/HELIOS_FFQB.xlsx")
# pid_list = helios_new$FREG0_PID
# food_new = filter(FFQ_food, FREG0_PID %in% pid_list)
# nutrition_new = filter(FFQ_nutrition, FREG0_PID %in% pid_list)
```
#species
```{r}
species = read_csv("data/abundance_bracken_standard_16_20221209_taxa_S_unfiltered_reads_decont2.csv")
#species$`SAM id`
helios_new_list = helios_new$FREG1_Barcode
#sample_list = metadata_micro$`Original Sample name`
micro_list <- filter(metadata_micro, metadata_micro$`Original Sample name` %in% helios_new_list)
species_new = filter(species, species$`SAM id` %in% micro_list$`Library ID`)
species_new
```

```{r}
new_merge = merge(metadata_micro, species_new, by.x = "Library ID", by.y = "SAM id")
#new_merge
species_meta = merge(x = helios_new[,c("FREG1_Barcode", "FREG5_Ethnic_Group", "FREG7_Gender", "FREG8_Age", "BMI", "BMI_groups")], y = new_merge, by.y = "Original Sample name", by.x = "FREG1_Barcode")
species_meta = species_meta %>% drop_na(FREG5_Ethnic_Group)
species_meta
```

```{r}
metadata = species_meta[, c("FREG1_Barcode", "FREG5_Ethnic_Group", "FREG7_Gender", "FREG8_Age", "BMI", "BMI_groups")]
metadata = metadata[!duplicated(metadata$FREG1_Barcode),]
metadata

drop = c("Library ID", "SampleType", "seq_batch", "DLAB25_Gluf_Mmol_L", "FREG5_Ethnic_Group","FREG10_Fasting_Hours", "FBP16_Caffeine", "FREG7_Gender", "FREG8_Age", "BMI", "BMI_groups")
species_data = species_meta[,!(names(species_meta) %in% drop)]
species_data  = species_data [!duplicated(species_data$FREG1_Barcode),]
species_data
```

```{r}
# write_xlsx(species_data, "data/species_866.xlsx")
# write_xlsx(metadata, "data/ethnicity_866.xlsx")
```

# merge 300 and 500 food
```{r}
food500 = read_csv("data/food_535.csv")
food300 = read_csv("data/HELIOS2_FFQA2024-06-29_redacted.csv")
colnames(food300)[1] ="Participant_ID"
food500
food300
```
```{r}
names(food500) <- tolower(names(food500))
names(food300) <- tolower(names(food300))


clean_colnames <- function(colnames) {
  # Remove the prefix "dffqa" followed by digits and an optional character and underscore
  colnames <- gsub("^dffqa\\d+(_\\d+|[a-zA-Z])?_?", "", colnames)
  # Remove the suffix "_serv_day" and "_g_per_day"
  colnames <- gsub("(_serv_day|_g_per_day)$", "", colnames)
  return(colnames)
}

# Apply the function to both data frames
colnames(food500) <- clean_colnames(colnames(food500))
colnames(food300) <- clean_colnames(colnames(food300))

names(food500)
names(food300)

```
```{r}
library(dplyr)
new_colnames <- c(
  "fried_rice_serv_day_adj" = "fried_rice_without_veg",
  "pasta_not_wholemeal" = "pasta_type_not_wholemeal",

  "pork_fresh_serv_day_fat" = "pork_fresh_fat",
  "pork_fresh_serv_day_lean" = "pork_fresh_lean",
  "beef_fresh_serv_day_fat" = "beef_fresh_fat",
  "beef_fresh_serv_day_lean" = "beef_fresh_lean",
  "mutton_serv_day_fat" = "mutton_fat",
  "mutton_serv_day_lean" = "mutton_lean",
  "not_100_fruit_juice" = "not_fruit_juice",
  "desserts_kueh_serv_day_coconut" = "desserts_kueh_coconut",
  "desserts_kueh_serv_day_nococonut" = "desserts_kueh_no_coconut",
  "desserts_in_soup_serv_day_coconut" = "desserts_in_soup_coconut",
  "desserts_in_soup_serv_day_nococonut" = "desserts_in_soup_no_coconut",
  "yoghurt" = "yoghurt_regular_fat",
  "cheese" = "cheese_regular_fat" 
)

food500_new <- food500 %>% rename_with(~ new_colnames[.x], .cols = names(new_colnames))

```


```{r}
common_columns <- intersect(names(food500_new), names(food300))

# Subset dataframes to include only common columns
df1_common <- food500_new[, common_columns, drop = FALSE]
df2_common <- food300[, common_columns, drop = FALSE]

# Bind the dataframes by rows
food800 <- rbind(df1_common, df2_common)

food800

```
```{r}
unique_to_df1 <- setdiff(names(food500_new), names(food300))

# Column names that are in df2 but not in df1
unique_to_df2 <- setdiff(names(food300), names(food500_new))

# Print the results
cat("Columns in df1 but not in df2:\n")
print(unique_to_df1)

cat("Columns in df2 but not in df1:\n")
print(unique_to_df2)
```



```{r}
#write_xlsx(food800, "data/all_food_863.xlsx")
```

```{r}
# Load necessary library
library(vegan)
food800 = read_xlsx("data/all_food_863.xlsx")
# eth = read_xlsx("data/helios800.xlsx")
# eth
# food800
# merge_food_eth = merge(eth[,c("FREG1_Barcode", "FREG5_Ethnic_Group")], food800, by.x = "FREG1_Barcode", by.y = "participant_id")
# merge_food_eth
```


```{r}
new = food800[,c(4:249)]
new[is.na(new)] <- 0 
#new <- na.omit(new)

distance_matrix <- dist(new, method = "euclidean")

# Perform PCoA
pcoa <- cmdscale(distance_matrix, eig = TRUE, k = 2)
 # k = 2 for 2 dimensions

# Combine the PCoA results with group information
pcoa_df <- as.data.frame(pcoa$points)

pcoa_df$Group <- factor(c(rep("First 535", 535), rep("Remaining 328", 328)))
#pcoa_df$Group <-  merge_food_eth$FREG5_Ethnic_Group
merge_food_eth
# Plot the PCoA results
library(ggplot2)
ggplot(pcoa_df, aes(x = V1, y = V2, color = Group)) +
  geom_point() +
  labs(title = "Old 535 Samples vs. new 328 Samples",
       x = "PCoA1",
       y = "PCoA2") +
  theme_minimal()

# Perform PERMANOVA to test for differences between groups
permanova_result <- adonis(distance_matrix ~ Group, data = pcoa_df)

# Display the PERMANOVA results
print(permanova_result)

```

```{r}
nutri800 = read_xlsx("data/FFQB800.xlsx")
nutri800
# Load necessary library
library(vegan)
new = nutri800[,c(2:20)]
new[is.na(new)] <- 0 
#new <- na.omit(new)

distance_matrix <- dist(new, method = "euclidean")

# Perform PCoA
pcoa <- cmdscale(distance_matrix, eig = TRUE, k = 2)
 # k = 2 for 2 dimensions

# Combine the PCoA results with group information
pcoa_df <- as.data.frame(pcoa$points)

pcoa_df$Group <- factor(c(rep("First 535", 534), rep("Remaining 328", 321)))

# Plot the PCoA results
library(ggplot2)
ggplot(pcoa_df, aes(x = V1, y = V2, color = Group)) +
  geom_point() +
  labs(title = "Old 535 Samples vs. new 328 Samples",
       x = "PCoA1",
       y = "PCoA2") +
  theme_minimal()

# Perform PERMANOVA to test for differences between groups
permanova_result <- adonis(distance_matrix ~ Group, data = pcoa_df)

# Display the PERMANOVA results
print(permanova_result)
```








