---
title: "network"
author: "Ruwen Zhou"
date: "6/19/2024"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(plyr)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(phyloseq)
library(vegan)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(ggraph)
library(igraph)
library(Hmisc)
```


#demographic
```{r}
food_data = read_csv("data/Summarized_Food_Categories_Only.csv")
nutrition_data = read_csv("data/nutrition_535.csv")
species = read_xlsx("data/species_535.xlsx")
metadata = read_csv("data/demo_535.csv")
metadata
nutrition_data
species
#metadata[,c("Participant_ID","FREG5_Ethnic_Group")]
```

```{r}
threshold <- nrow(species) * 0.1

species_filtered <- species %>% select_if(function(x) sum(x > 0) > threshold)

abundance_threshold <- 0.0001
species_filtered2 <- species_filtered %>% select_if(function(x) sum(x) > (abundance_threshold * sum(species)))

species_filtered2
```


```{r}
species_filtered2 = subset(species_filtered2, select = -c(unclassified, others))
full_data <- merge(food_data, species_filtered2, by="Participant_ID")
full_data <- merge(full_data, nutrition_data, by="Participant_ID")
full_data
```

```{r}
nutrition_columns <- names(nutrition_data)[-1]  
species_columns <- names(species_filtered2)[-1] 
food_columns <- names(food_data)[-1]

```


```{r}
food_species_data <- full_data[, c(food_columns, species_columns)]
nutrition_species_data <- full_data[, c(nutrition_columns, species_columns)]

calculate_significant_correlations <- function(data, food_or_nutrition_columns, species_columns) {
  cor_results <- rcorr(as.matrix(data), type = "spearman")
  adjusted_p_values <- matrix(p.adjust(cor_results$P, method = "BH"), nrow = nrow(cor_results$P))
  significant_indices <- which(adjusted_p_values < 0.01, arr.ind = TRUE)
  
  significant_correlations <- data.frame(
    from = colnames(data)[significant_indices[, "row"]],
    to = colnames(data)[significant_indices[, "col"]],
    correlation = cor_results$r[significant_indices],
    adjusted_p_value = adjusted_p_values[significant_indices]
  )
  
  significant_correlations <- significant_correlations[
    significant_correlations$from %in% food_or_nutrition_columns & significant_correlations$to %in% species_columns |
    significant_correlations$from %in% species_columns & significant_correlations$to %in% food_or_nutrition_columns, ]
  
  return(significant_correlations)
}
```


```{r}

significant_food_species_correlations <- calculate_significant_correlations(food_species_data, food_columns, species_columns)
significant_nutrition_species_correlations <- calculate_significant_correlations(nutrition_species_data, nutrition_columns, species_columns)

print(significant_food_species_correlations)
print(significant_nutrition_species_correlations)

```

```{r}
combine_t = rbind(significant_food_species_correlations, significant_nutrition_species_correlations)

combine_t  <- combine_t  %>%
  mutate(
    node1 = pmin(from, to),
    node2 = pmax(from, to)
  ) %>%
  distinct(node1, node2, .keep_all = TRUE)  # keep one of each unique pair


combine_t
```
```{r}
cor_data <- combine_t  %>%
  mutate(edge_color = ifelse(correlation > 0, "red", "cadetblue2"),
         abs_correlation = abs(correlation))

# Add a column for node shapes
# cor_data <- cor_data %>%
#   mutate(from_shape = ifelse(from %in% food_columns, "square", ifelse(from %in% nutrition_columns, "triangle", "circle")),
#          to_shape = ifelse(to %in% food_columns, "square", ifelse(to %in% nutrition_columns, "triangle", "circle")))
cor_data
```
```{r}
nodes <- unique(c(cor_data$from, cor_data$to))

node_info <- data.frame(
  name = nodes,
  type = ifelse(nodes %in% species_columns, "Species",
                ifelse(nodes %in% food_columns, "Food", "Nutrition"))
)

node_info$name <- as.character(node_info$name)
node_info
```
```{r}
edge_list <- cor_data %>% select(from, to, edge_color, abs_correlation)
edge_list
graph <- graph_from_data_frame(d = edge_list, vertices = node_info, directed = FALSE)

V(graph)$shape <- ifelse(V(graph)$type == "Species", "circle",
                         ifelse(V(graph)$type == "Food", "square", "diamond"))

V(graph)$degree <- degree(graph, mode = "all")
#plot(graph)
node_info
```


```{r fig.width=14, fig.height=14}
full_graph = ggraph(graph, layout = "fr") +  # 'fr' can be changed to another layout if needed
  geom_edge_link(aes(edge_alpha = abs_correlation, edge_width = abs_correlation, edge_color = edge_color), show.legend = FALSE) +
  geom_node_point(aes(shape = shape, size = degree , color = shape)) +
  geom_node_text(aes(label = name), repel = TRUE, fontface = "bold", color = "black", size = 3) +
  scale_size(range = c(4, 10)) + 
  scale_shape_manual(values = c(circle = 19, square = 15, diamond = 17), labels = c("Species", "Nutrition", "Food")) +
  scale_edge_color_manual(values = c("#8D3256", "#004697")) +
  scale_color_manual(values = c("slateblue", "#68B69F", "#F08E59"), labels = c("Species", "Nutrition", "Food")) +
  theme_graph() +
  theme(legend.position = "right") +
  ggtitle("Correlation Network between Species, Food, and Nutrition")
```


```{r}
png("figure/network_all.png", width = 1400, height = 1400, res = 120)
full_graph
dev.off()
```



# seperate ethnic groups

```{r}
new_full <- merge(metadata[,c("Participant_ID","FREG5_Ethnic_Group","FREG7_Gender", "FREG8_Age", "BMI", "BMI_groups")],full_data, by="Participant_ID")
df_cm <- new_full %>% filter(FREG5_Ethnic_Group == "C" | FREG5_Ethnic_Group == "M")
df_im <- new_full %>% filter(FREG5_Ethnic_Group == "I" | FREG5_Ethnic_Group == "M")
# data_c <- new_full %>% filter(FREG5_Ethnic_Group == "C")
# data_i <- new_full %>% filter(FREG5_Ethnic_Group == "I")
# data_m <- new_full %>% filter(FREG5_Ethnic_Group == "M")
df_cm$groupM_C <- ifelse(df_cm$FREG5_Ethnic_Group == "M", 1,
                      ifelse(df_cm$FREG5_Ethnic_Group == "C", 0, NA))
df_im$groupM_I <- ifelse(df_im$FREG5_Ethnic_Group == "M", 1,
                      ifelse(df_im$FREG5_Ethnic_Group == "I", 0, NA))
# data_c <- new_full %>% filter(FREG5_Ethnic_Group == "C")
# data_i <- new_full %>% filter(FREG5_Ethnic_Group == "I")
# data_m <- new_full %>% filter(FREG5_Ethnic_Group == "M")
```

```{r}
library(MatchIt)
#library(tableone)

m.out_C <- matchit(groupM_C ~ FREG7_Gender + FREG8_Age + BMI_groups,
                   data = df_cm, method = "nearest", ratio = 1,
                   #exact = c("FREG7_Gender", "BMI_groups"),
                   caliper = 0.1)
summary(m.out_C)
matched_data_C <- match.data(m.out_C)
matched_data_C
```


```{r}
m.out_I <- matchit(groupM_I ~ FREG7_Gender + FREG8_Age + BMI_groups,
                   data = df_im, method = "nearest", ratio = 1,
                   #exact = c("FREG7_Gender"),
                   caliper = 0.4)
summary(m.out_I)
matched_data_I <- match.data(m.out_I)
#matched_data_I
```

```{r}
data_c <- matched_data_C %>% filter(FREG5_Ethnic_Group == "C")
data_i <- matched_data_I %>% filter(FREG5_Ethnic_Group == "I")
data_m <- matched_data_C %>% filter(FREG5_Ethnic_Group == "M")
```

```{r}
data_c
data_i
data_m
```


# unweighted
```{r}
calculate_significant_correlations <- function(data, food_or_nutrition_columns, species_columns) {
  cor_results <- rcorr(as.matrix(data), type = "spearman")
  adjusted_p_values <- matrix(p.adjust(cor_results$P, method = "BH"), nrow = nrow(cor_results$P))
  significant_indices <- which(adjusted_p_values < 0.05, arr.ind = TRUE)

  significant_correlations <- data.frame(
    from = colnames(data)[significant_indices[, "row"]],
    to = colnames(data)[significant_indices[, "col"]],
    correlation = cor_results$r[significant_indices],
    adjusted_p_value = adjusted_p_values[significant_indices]
  )

  significant_correlations <- significant_correlations[
    significant_correlations$from %in% food_or_nutrition_columns & significant_correlations$to %in% species_columns |
    significant_correlations$from %in% species_columns & significant_correlations$to %in% food_or_nutrition_columns, ]

  return(significant_correlations)}

```
# weighted
```{r}
# library(wCorr)  # Ensure this package is loaded
# 
# calculate_significant_correlations <- function(data, food_or_nutrition_columns, species_columns, weights) {
#   # Extract the relevant columns for the analysis
#   analysis_data <- data[, c(food_or_nutrition_columns, species_columns)]
#   
#   # Convert to numeric matrix if not already
#   analysis_data[] <- lapply(analysis_data, function(x) as.numeric(as.character(x)))
#   
#   # Prepare empty matrices for correlation and p-values
#   correlation_matrix <- matrix(0, nrow = ncol(analysis_data), ncol = ncol(analysis_data))
#   p_value_matrix <- matrix(0, nrow = ncol(analysis_data), ncol = ncol(analysis_data))
#   
#   # Calculate weighted correlations for each pair of columns
#   for (i in 1:ncol(analysis_data)) {
#     for (j in i:ncol(analysis_data)) {
#       if (i != j) {
#         # Assuming weightedCorr returns a list with 'estimate' and 'p.value'
#         corr_result <- weightedCorr(analysis_data[, i], analysis_data[, j], method = "Spearman", weights = weights)
#         correlation_matrix[i, j] <- corr_result$estimate
#         correlation_matrix[j, i] <- corr_result$estimate  # Symmetric matrix
#         p_value_matrix[i, j] <- corr_result$p.value
#         p_value_matrix[j, i] <- corr_result$p.value  # Symmetric matrix
#       } else {
#         correlation_matrix[i, j] <- 1  # Diagonal elements are perfect correlations
#         p_value_matrix[i, j] <- 0  # Diagonal elements p-value of correlation with itself
#       }
#     }
#   }
#   
#   # Adjust p-values using BH method
#   adjusted_p_values <- p.adjust(as.vector(p_value_matrix), method = "BH")
#   adjusted_p_matrix <- matrix(adjusted_p_values, nrow = ncol(analysis_data))
#   
#   # Identify significant correlations
#   significant_indices <- which(adjusted_p_matrix < 0.05, arr.ind = TRUE)
#   
#   # Create a dataframe of significant correlations
#   significant_correlations <- data.frame(
#     from = colnames(analysis_data)[significant_indices[, 1]],
#     to = colnames(analysis_data)[significant_indices[, 2]],
#     correlation = correlation_matrix[significant_indices],
#     adjusted_p_value = adjusted_p_matrix[significant_indices]
#   )
#   
#   # Filter to include only food-species interactions
#   significant_correlations <- significant_correlations[
#     (significant_correlations$from %in% food_or_nutrition_columns & significant_correlations$to %in% species_columns) |
#     (significant_correlations$from %in% species_columns & significant_correlations$to %in% food_or_nutrition_columns), ]
#   
#   return(significant_correlations)
# }

```

# chinese
```{r}
# set.seed(123) 
# 
# selected_indices <- sample(nrow(data_c), 49)
# 
# # Subset the DataFrame to get the selected rows
# data_c_49 <- data_c[selected_indices, ]
# data_c_49
```


```{r}
food_species_c <- data_c[, c(food_columns, species_columns)]
nutrition_species_c <- data_c[, c(nutrition_columns, species_columns)]

food_species_correlations_c <- calculate_significant_correlations(food_species_c, food_columns, species_columns)
nutrition_species_correlations_c <- calculate_significant_correlations(nutrition_species_c, nutrition_columns, species_columns)
```
```{r}
combine_c = rbind(food_species_correlations_c, nutrition_species_correlations_c)

combine_c  <- combine_c  %>%
  mutate(
    node1 = pmin(from, to),
    node2 = pmax(from, to)
  ) %>%
  distinct(node1, node2, .keep_all = TRUE)  # keep one of each unique pair
combine_c
```
```{r}
cor_data_c <- combine_c  %>%
  mutate(edge_color = ifelse(correlation > 0, "red", "blue"),
         abs_correlation = abs(correlation),
         log_p = -log10(adjusted_p_value))


cor_data_c
```

# indian
```{r}
# set.seed(123) 
# 
# selected_indices <- sample(nrow(data_i), 49)
# 
# # Subset the DataFrame to get the selected rows
# data_i_49 <- data_c[selected_indices, ]
# data_i_49
```


```{r}
food_species_i <- data_i[, c(food_columns, species_columns)]
nutrition_species_i <- data_i[, c(nutrition_columns, species_columns)]


food_species_correlations_i <- calculate_significant_correlations(food_species_i, food_columns, species_columns)
nutrition_species_correlations_i <- calculate_significant_correlations(nutrition_species_i, nutrition_columns, species_columns)
```
```{r}
combine_i = rbind(food_species_correlations_i, nutrition_species_correlations_i)

combine_i  <- combine_i  %>%
  mutate(
    node1 = pmin(from, to),
    node2 = pmax(from, to)
  ) %>%
  distinct(node1, node2, .keep_all = TRUE)  # keep one of each unique pair
combine_i
```
```{r}
cor_data_i <- combine_i  %>%
  mutate(edge_color = ifelse(correlation > 0, "red", "blue"),
         abs_correlation = abs(correlation),
         log_p = -log10(adjusted_p_value))


cor_data_i
```

# malays
```{r}
food_species_m <- data_m[, c(food_columns, species_columns)]
nutrition_species_m <- data_m[, c(nutrition_columns, species_columns)]


food_species_correlations_m <- calculate_significant_correlations(food_species_m, food_columns, species_columns)
nutrition_species_correlations_m <- calculate_significant_correlations(nutrition_species_m, nutrition_columns, species_columns)
```

```{r}
combine_m = rbind(food_species_correlations_m, nutrition_species_correlations_m)

combine_m  <- combine_m  %>%
  mutate(
    node1 = pmin(from, to),
    node2 = pmax(from, to)
  ) %>%
  distinct(node1, node2, .keep_all = TRUE)  # keep one of each unique pair
combine_m
```
```{r}
cor_data_m <- combine_m  %>%
  mutate(edge_color = ifelse(correlation > 0, "red", "blue"),
         abs_correlation = abs(correlation),
         log_p = -log10(adjusted_p_value))


cor_data_m
```

## power analysis
```{r}
# library(pwr)
# r_observed <- 0.1 
# result <- pwr.r.test(n = NULL, r = r_observed, sig.level = 0.05, power = 0.80, alternative = "two.sided")
# print(result)

```



# find out the nodes we need


```{r}
library(ggraph)
library(tidygraph)

# Assuming cor_data_c, cor_data_i, cor_data_m are data frames with columns: from, to, edge_color, log_p

all_nodes <- unique(c(cor_data_c$from, cor_data_c$to, cor_data_i$from, cor_data_i$to, cor_data_m$from, cor_data_m$to))

# Create a nodes data frame
nodes_df <- data.frame(name = unique(all_nodes))
nodes_df$shape <- ifelse(nodes_df$name %in% species_columns, "circle", 
                         ifelse(nodes_df$name %in% food_columns, "square", "diamond"))



# Create graph objects from edge lists and nodes
graph_c <- tbl_graph(edges = cor_data_c, nodes = nodes_df, directed = FALSE)
graph_i <- tbl_graph(edges = cor_data_i, nodes = nodes_df, directed = FALSE)
graph_m <- tbl_graph(edges = cor_data_m, nodes = nodes_df, directed = FALSE)

  

plot_graph <- function(graph) {
  ggraph(graph, layout = "fr") +
    geom_edge_link(aes(edge_alpha = abs_correlation, edge_color = edge_color, edge_width = abs_correlation), show.legend = FALSE) +
    geom_node_point(aes(shape = shape), size = 5) +
    scale_shape_manual(values = c(circle = 16, square = 15, diamond = 18), labels = c("Species","Nutrition", "Food")) +  # Mapping shapes to actual ggplot2 shapes
    theme_minimal() +
    scale_edge_color_manual(values = c("red", "blue"))
}

# Plot each graph
plot_c <- plot_graph(graph_c)
plot_i <- plot_graph(graph_i)
plot_m <- plot_graph(graph_m)

# Print plots
print(plot_c)
print(plot_i)
print(plot_m)

```
```{r}

all_nodes <- unique(c(cor_data_c$from, cor_data_c$to, cor_data_i$from, cor_data_i$to, cor_data_m$from, cor_data_m$to))

nodes_df <- data.frame(name = unique(all_nodes))
nodes_df$shape <- ifelse(nodes_df$name %in% species_columns, "circle", 
                         ifelse(nodes_df$name %in% food_columns, "square", "diamond"))

all_edges <- bind_rows(
  mutate(cor_data_c, graph = 'c'),
  mutate(cor_data_i, graph = 'i'),
  mutate(cor_data_m, graph = 'm')
)


combined_graph <- tbl_graph(edges = all_edges, nodes = nodes_df, directed = FALSE)

fixed_layout <- create_layout(combined_graph, layout = "fr")

nodes_df <- left_join(nodes_df, data.frame(name = nodes_df$name, x = fixed_layout$x, y = fixed_layout$y), by = "name")

graph_c <- tbl_graph(edges = cor_data_c, nodes = nodes_df, directed = FALSE)
graph_i <- tbl_graph(edges = cor_data_i, nodes = nodes_df, directed = FALSE)
graph_m <- tbl_graph(edges = cor_data_m, nodes = nodes_df, directed = FALSE)

# plot_graph_fixed <- function(graph) {
#   # Convert igraph object to tbl_graph (tidygraph object)
#   tbl_graph <- as_tbl_graph(graph)
#   
#   # Use mutate to add degree centrality
#   tbl_graph <- tbl_graph %>%
#     activate(nodes) %>%
#     mutate(degree = centrality_degree(mode = "all"))  # Use mode="all", "in", or "out" as needed
#   
#   # Create the plot
#   ggraph(tbl_graph, layout = 'manual', x = x, y = y) +
#     geom_edge_link(aes(edge_alpha = log_p, edge_color = edge_color, edge_width = log_p), show.legend = FALSE) +
#     geom_node_point(aes(shape = shape, size = degree, color = label), color = "black") +
#     scale_shape_manual(values = c(circle = 16, square = 15, diamond = 18), labels = c("Species","Nutrition", "Food")) +
#     theme_graph() +
#     scale_edge_color_manual(values = c("red", "blue")) +
#     scale_size(range = c(3, 10)) +
#     scale_color_manual(values = c("Species" = "green", "Nutrition" = "orange", "Food" = "purple"))
# }


plot_graph_fixed <- function(graph) {
  # Calculate the degree of each node
  V(graph)$degree <- degree(graph, mode = "all")
  V(graph)$shape <- ifelse(V(graph)$name %in% species_columns, "circle", 
                         ifelse(V(graph)$name %in% food_columns, "square", "diamond"))

  # Create the plot
  ggraph(graph, layout = 'manual', x = x, y = y) +
    geom_edge_link(aes(edge_alpha = abs_correlation, edge_color = edge_color, edge_width = abs_correlation), show.legend = FALSE) +
    geom_node_point(aes(shape = shape, size = degree, color = shape)) +  # Map 'size' to 'degree'
    geom_node_text(aes(label = ifelse(degree > 0, name, "")), , color = "black", repel = TRUE, fontface = "bold", size = 3) +
    scale_shape_manual(values = c(circle = 19, square = 15, diamond = 17), labels = c("Species", "Nutrition", "Food")) +
    scale_edge_color_manual(values = c("#8D3256", "#004697")) +
    scale_color_manual(values = c("slateblue", "#68B69F", "#F08E59"), labels = c("Species", "Nutrition", "Food")) +
    theme_graph() +
    scale_size(range = c(4, 7))
}
#V(graph)$shape <- ifelse(V(graph)$type == "Species", "circle",
                         #ifelse(V(graph)$type == "Food", "square", "diamond"))

plot_c_fixed <- plot_graph_fixed(graph_c)
plot_i_fixed <- plot_graph_fixed(graph_i)
plot_m_fixed <- plot_graph_fixed(graph_m)


print(plot_c_fixed)
print(plot_i_fixed)
print(plot_m_fixed)

```
```{r fig.width=10, fig.height=10}
png("figure/network_c_49.png", width = 1400, height = 1400, res = 120)
plot_c_fixed
dev.off()
png("figure/network_i_49.png", width = 1400, height = 1400, res = 120)
plot_i_fixed
dev.off()
png("figure/network_m_49.png", width = 1400, height = 1400, res = 120)
plot_m_fixed
dev.off()
```

## try bubble
```{r}
library(igraph)
library(ggraph)
library(tidygraph)
library(dplyr)

# Combine and prepare nodes and edges
all_nodes <- unique(c(cor_data_c$from, cor_data_c$to, cor_data_i$from, cor_data_i$to, cor_data_m$from, cor_data_m$to))
nodes_df <- data.frame(name = unique(all_nodes))
nodes_df$shape <- ifelse(nodes_df$name %in% species_columns, "circle", 
                         ifelse(nodes_df$name %in% food_columns, "square", "diamond"))

all_edges <- bind_rows(
  mutate(cor_data_c, graph = 'c'),
  mutate(cor_data_i, graph = 'i'),
  mutate(cor_data_m, graph = 'm')
)

combined_graph <- tbl_graph(edges = all_edges, nodes = nodes_df, directed = FALSE)
fixed_layout <- create_layout(combined_graph, layout = "fr")
nodes_df <- left_join(nodes_df, data.frame(name = nodes_df$name, x = fixed_layout$x, y = fixed_layout$y), by = "name")

graph_c <- tbl_graph(edges = cor_data_c, nodes = nodes_df, directed = FALSE)
graph_i <- tbl_graph(edges = cor_data_i, nodes = nodes_df, directed = FALSE)
graph_m <- tbl_graph(edges = cor_data_m, nodes = nodes_df, directed = FALSE)

# Function to calculate components and add them to the nodes
add_component_membership <- function(graph) {
  components <- components(graph)
  V(graph)$component <- components$membership
  return(graph)
}

# Apply the function to each graph
graph_c <- add_component_membership(graph_c)
graph_i <- add_component_membership(graph_i)
graph_m <- add_component_membership(graph_m)

# Function to calculate and assign degree
assign_degree <- function(graph) {
  V(graph)$degree <- degree(graph, mode = "all")
  return(graph)
}

# Apply the function to each graph
graph_c <- assign_degree(graph_c)
graph_i <- assign_degree(graph_i)
graph_m <- assign_degree(graph_m)
```


```{r fig.width=10, fig.height=8}
plot_graph_fixed <- function(graph) {
  node_data <- as_tibble(as_data_frame(graph, what = "vertices"))
  ggraph(graph, layout = 'manual', x = node_data$x, y = node_data$y) +
    geom_edge_link(aes(edge_alpha = abs_correlation, edge_color = edge_color, edge_width = abs_correlation), show.legend = FALSE) +
    geom_node_point(aes(shape = shape, size = degree, color = as.factor(component)), show.legend = FALSE) +  # Map 'color' to 'component'
    geom_node_text(aes(label = ifelse(degree > 0, name, "")), color = "black", repel = TRUE, fontface = "bold", size = 3) +
    scale_shape_manual(values = c(circle = 19, square = 15, diamond = 17), labels = c("Species", "Nutrition", "Food")) +
    scale_edge_color_manual(values = c("#8D3256", "#004697")) +
    scale_color_discrete() +  # Use discrete color scale for components
    theme_graph() +
    scale_size(range = c(4, 7))
}

# Plot each graph with the fixed layout
plot_c_fixed_new <- plot_graph_fixed(graph_c)
plot_i_fixed_new <- plot_graph_fixed(graph_i)
plot_m_fixed_new <- plot_graph_fixed(graph_m)

print(plot_c_fixed_new)
print(plot_i_fixed_new)
print(plot_m_fixed_new)


```
```{r}
png("figure/network_c_new.png", width = 1400, height = 1400, res = 120)
plot_c_fixed_new
dev.off()
png("figure/network_i_new.png", width = 1400, height = 1400, res = 120)
plot_i_fixed_new
dev.off()
png("figure/network_m_new.png", width = 1400, height = 1400, res = 120)
plot_m_fixed_new
dev.off()
```






## normality test for each food
```{r}
distri_food = full_data[,-1]

distri_food = subset(distri_food, FREG5_Ethnic_Group != "O")

# Assuming 'full_data' has one row per participant and multiple food intake columns
# Reshape the data from wide to long format
long_data <- distri_food %>%
  pivot_longer(
    cols = -FREG5_Ethnic_Group,  # Exclude the group column
    names_to = "Food_Type",       # New column for food types
    values_to = "Intake"          # New column for intake values
  )
```


```{r}

food_types <- c("Fish", "Crustacean", "Mollusk", "Seafood_dishes", "Poultry", "Red_meat",
                "Meat_dishes", "Processed_meat", "Dairy", "Cruciferous_vegetables", "Legumes",
                "Mushroom", "Fruits", "Wholegrain", "Chapati", "Noodle_dishes", "Deep_fried", 
                "Coffee", "Tea")

# if (!dir.exists("figure")) {
#   dir.create("figure")
# }


for (food in food_types) {
  current_data <- long_data %>% filter(Food_Type == food)
  p <- ggplot(current_data, aes(x = Intake, fill = FREG5_Ethnic_Group)) +
    geom_density(alpha = 0.5, adjust = 1.5) +
    labs(title = paste("Density Plot of", food),
         x = "Intake per Day", y = "Density") +
    scale_fill_manual(values = c("C" = "#9FDDCA", "I" = "#9EA3F1", "M" = "#E17887")) +
    theme_minimal()+
    theme(legend.position = "none",
          plot.title = element_text(size = 20, face = "bold"))
  png_filename <- paste0("figure/", food, "_density_plot.png")
  ggsave(png_filename, plot = p, width = 10, height = 6, dpi = 300)
}

```


```{r}
library(patchwork)
# Define the vector of food types
food_types <- c("Fish", "Crustacean", "Mollusk", "Seafood_dishes", "Poultry", "Red_meat",
                "Meat_dishes", "Processed_meat", "Dairy", "Cruciferous_vegetables", "Legumes",
                "Mushroom", "Fruits", "Wholegrain", "Chapati", "Noodle_dishes", "Deep_fried", 
                "Coffee", "Tea")

# Initialize an empty list to store plots
plots_list <- list()

# Loop through each food type and create a plot
for (food in food_types) {
  current_data <- long_data %>% filter(Food_Type == food)
  
  p <- ggplot(current_data, aes(x = Intake, fill = FREG5_Ethnic_Group)) +
    geom_density(alpha = 0.5, adjust = 1.5) +
    labs(title = paste(food),
         x = "Intake per Day", y = "Density") +
    scale_fill_manual(values = c("C" = "#9FDDCA", "I" = "#9EA3F1", "M" = "#E17887")) +
    theme_minimal()+
    theme(legend.position = "none")
  
  # Add the plot to the list
  plots_list[[food]] = p
}

# Combine all plots side by side using patchwork
combined_plot <- wrap_plots(plots_list, ncol = 1) # Adjust ncol to change the number of columns
combined_plot
# Save the combined plot
#ggsave("combined_density_plots.png", combined_plot, width = 30, height = 20, dpi = 300) # Adjust size as needed

```

## circular plot
```{r}
total_graph <-
  tidygraph::tbl_graph(nodes = node_data,
                       edges = edge_data,
                       directed = TRUE) %>%
  dplyr::mutate(Degree = centrality_degree(mode = 'all'))

pal <-
  wesanderson::wes_palette(name = "Zissou1", n = 100, type = "continuous")

library(igraph)

g <- total_graph

V(g)$type <- bipartite_mapping(g)$type

coords <- 
  create_layout(g, layout = "bipartite") %>%
  dplyr::select(x, y) 

# coords$index <- 1:nrow(coords)
# coords <-
#   coords %>% 
#   dplyr::arrange(x)
# 
# coords$x[coords$y == 0] <- 
#   seq(0, 332, length.out = sum(coords$y == 0))
# 
# coords$x[coords$y == 1] <- 
#   seq(0, 332, length.out = sum(coords$y == 1))

coords$y[coords$y == 0] <- 0.3

coords <- 
coords %>% 
  dplyr::select(x,y) %>% 
  dplyr::mutate(theta = x / (max(x) + 1) * 2 * pi,
         r = y + 1, 
         x = r * cos(theta), 
         y = r * sin(theta))

my_graph <-
  create_layout(graph = g,
                layout = "manual", 
                x = coords$x,
                y = coords$y
                # node.position = coords
                )

plot <-
  ggraph(my_graph,
         layout = 'bipartite') +
  geom_edge_link(aes(color = Correlation),
                 show.legend = TRUE) +
  geom_node_point(
    aes(fill = Class,
        size = Degree,
        alpha = Class),
    shape = 21,
    # alpha = 0.6,
    show.legend = TRUE
  ) +
  scale_fill_manual(values = value) +
  scale_color_manual(values = value) +
  scale_alpha_manual(values = alpha_value) +
  geom_node_text(
    aes(
      x = x * 1.03,
      y = y * 1.03,
      label = ifelse(Class == "Gut microbiome", true_name, true_name),
      hjust = ifelse(Class == "Gut microbiome", "inward",'outward'),
      angle = -((-node_angle(x, y) + 90) %% 180) + 90,
      size = ifelse(Class == "Gut microbiome", 2, 4),
      # size = 1,
      colour = Class
    ),repel = FALSE,
    # size = 3,
    alpha = 1,
    show.legend = FALSE
  ) +
  guides(
    edge_width = guide_legend(title = "-log10(FDR adjusted P value)",
                              override.aes = list(shape = NA)),
    edge_color = ggraph::guide_edge_colorbar(title = "Spearman correlation"),
    fill = guide_legend(
      title = "Class",
      override.aes = list(size = 7, linetype = "blank")
    ),
    size = guide_legend(title = "Degree", override.aes = list(linetype = 0))
  ) +
  ggraph::scale_edge_color_gradientn(colours = pal) +
  ggraph::scale_edge_width(range = c(0.2, 2)) +
  scale_size_continuous(range = c(0.5, 5)) +
  theme_void() +
  theme(
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.background = element_rect(fill = "transparent", color = NA)
  )

plot
```








